version: '2'
services:
    taskapplication-app:
        image: taskapplication
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://taskapplication-mysql:3306/taskapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    taskapplication-mysql:
        extends:
            file: mysql.yml
            service: taskapplication-mysql
